### ISSUE TITLE
Doesn’t work for 21.04 anymore

### ISSUE THREAD

**Issue by DominicWoozy** [mtbiker-s/ubuntu20.10-rpi-install-vnc#2]
Please help!

**Comment by mtbiker-s** [comment]
Hi @DominicWoozy, I don’t currently have a Pi setup with 21.04, need to build one. Can you provide any errors you are seeing?
I appreciate it.

**Comment by maurop88** [comment]
If it helps, I did run this script in a pi 4 running Ubuntu 21.04 64 bits, updated & upgraded yesterday, and it works perfectly!

**Comment by mtbiker-s** [comment]
Thank you @maurop88 for testing it out, really appreciate it. Did you need to do anything to the scripts to get it to work or did you just run is as it is? Were the upgrades to the script or to your version of Ubuntu for RPi? Let me know, would like to update the documentation that it works ok on with Ubuntu 21.04 64 bit version for Raspberry Pi. Let me know if you have any questions.

**Comment by maurop88** [comment]
@mtbiker-s I did not change anything to the script! But I tried different things before running it. This is what I remember:

1. Clean install of Ubuntu 21.04 64 bits for pi 4 image 
2. apt update && apt upgrade 
3. Manually installed de lates vnc-server .deb form the official page
4. Copied the .so files from [raspberry firmware github](https://github.com/raspberrypi/firmware/tree/master/opt/vc/lib) to the lib folder
5. Run the vnclicensewiz, which failed to register device after login
6. Found your script and run it, which replaced the deb with a previous version and created the .so symlinks
7. **Uncommented `“WaylandEnable=false”` in `/etc/gdm3/custom.conf`**
8. Rebooted and everything worked
9. Deleted the .so files that I manually copied before
10. Everything kept working

From this, I can assume that the previous installation of deb and the .so files I manually copied did not do anything to make it work. If that is true, then just running the script on a clean install and making sure `WaylandEnabled=false` should make it work. If I had found this script earlier, it should have been much easier!

**Comment by mtbiker-s** [comment]
@maurop88 thank you for the insight on that. Interesting that modifying **gdm3** (Gnome Display Manager) [https://manpages.ubuntu.com/manpages/xenial/man8/gdm3.8.html](https://manpages.ubuntu.com/manpages/xenial/man8/gdm3.8.html) made it work on Ubuntu 21.04, I'll ask @DominicWoozy to see if he can modify his custom.conf file under /etc/gdm3. For me on Ubuntu 20.10 I have **WaylandEnable=false** commented out. That could be the thing that fixes it. I will do a backup of my 20.10 and update to 21.04 when I get a chance to test this out. Thank you again for testing this ou and passing on the fix. Once I have the modifications to script tested on the new version I'll post it up.

**Comment by mtbiker-s** [comment]
@DominicWoozy would you be able to test modifying the file **custom.conf** under /etc/gdm3 and uncomment the line that reads **WaylandEnabled=false** save it and then run the script to see if the VNC piece works for you. This seemed to work for @maurop88 , this was what he did to make it work under RPi Ubuntu 21.04. Please make sure to do a backup of your custom.conf file first though. Let me know if that works for you. I appreciate your time.

**Comment by mtbiker-s** [comment]
Modified script based on findings by @maurop88. Updated to Hirsute Hippo on RPi, ran script then modified /etc/gdm3/custom.conf to un-comment "WaylanEnabled=false". Added all this to program and tested, VNC is working on Ubuntu RPi Hirsute Hippo 21.04

**Comment by mtbiker-s** [comment]
@DominicWoozy the script is working again. Hopefully you've resolved your issue with VNC but if not this should help out, I hope :)
