### ISSUE TITLE
Missing libraspberrypi0 dependency on clean ubuntu server install

### ISSUE THREAD

**Issue by b-around** [mtbiker-s/ubuntu20.10-rpi-install-vnc#4]
See below a dependency issue when running the script on a clean Ubuntu for raspberryPi distro.

STEPS TO REPRODUCE
1) clean install of Ubuntu Server 21.04 64-bit from https://ubuntu.com/download/raspberry-pi

2) install ubuntu desktop
$ sudo apt install ubuntu-desktop

3) disable desktop mode auto-start as this is a headless raspberrypi and most of the times will work in server only mode (loading desktop wastes resources)
$ systemctl set-default multi-user.target

3) do a set up updates to the OS
$ sudo apt update
$ sudo apt upgrade
$ sudo apt autoremove
$ sudo reboot

3) run the realvnc installation script as instructed and check for the errors as per OUTPUT below
$ sudo ./install-real-vnc-server-rpi4-8gb-ubuntu.sh

OUTPUT
====================================
No LSB modules are available.
You are about to install RealVNC Server for RaspberryPi4 8gb
realvnc-vnc-server_6.7.2.43081_arm64.deb

Checking to see if this version of Ubuntu for RaspberryPi is supported by script...
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
is supported by this script.
Would you like to continue?
Enter 'y' for yes or 'n' for No :
y

Installing VNC Server : "realvnc-vnc-server_6.7.2.43081_arm64.deb"...
--2021-08-25 14:21:45--  https://archive.raspberrypi.org/debian/pool/main/r/realvnc-vnc/realvnc-vnc-server_6.7.2.43081_arm64.deb
Resolving archive.raspberrypi.org (archive.raspberrypi.org)... 93.93.135.117, 93.93.130.212, 46.235.227.39, ...
Connecting to archive.raspberrypi.org (archive.raspberrypi.org)|93.93.135.117|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9075008 (8.7M) [application/x-debian-package]
Saving to: ‘realvnc-vnc-server_6.7.2.43081_arm64.deb’

realvnc-vnc-server_6.7.2.4308 100%[=================================================>]   8.65M  13.0MB/s    in 0.7s

2021-08-25 14:21:46 (13.0 MB/s) - ‘realvnc-vnc-server_6.7.2.43081_arm64.deb’ saved [9075008/9075008]

Selecting previously unselected package realvnc-vnc-server.
(Reading database ... 179173 files and directories currently installed.)
Preparing to unpack realvnc-vnc-server_6.7.2.43081_arm64.deb ...
Unpacking realvnc-vnc-server (6.7.2.43081) ...
dpkg: dependency problems prevent configuration of realvnc-vnc-server:
 realvnc-vnc-server depends on libraspberrypi0; however:
  Package libraspberrypi0 is not installed.

dpkg: error processing package realvnc-vnc-server (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.68ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for shared-mime-info (2.0-1) ...
Errors were encountered while processing:
 realvnc-vnc-server

Creating symlink for the following files :
attempting to create symlink file "/usr/lib/libvchiq_arm.so.0"...
attempting to create symlink file "/usr/lib/libbcm_host.so.0"...
attempting to create symlink file "/usr/lib/libvcos.so.0"...
attempting to create symlink file "/usr/lib/libmmal.so.0"...
attempting to create symlink file "/usr/lib/libmmal_core.so.0"...
attempting to create symlink file "/usr/lib/libmmal_components.so.0"...
attempting to create symlink file "/usr/lib/libmmal_util.so.0"...
attempting to create symlink file "/usr/lib/libmmal_vc_client.so.0"...
attempting to create symlink file "/usr/lib/libvcsm.so.0"...
attempting to create symlink file "/usr/lib/libcontainers.so.0"...

Enabling and starting the necessary services...
Enabling and starting the service "vncserver-virtuald.service"...
Failed to enable unit: Unit file vncserver-virtuald.service does not exist.
Failed to start vncserver-virtuald.service: Unit vncserver-virtuald.service not found.
Enabling and starting the service "vncserver-x11-serviced.service"...
Failed to enable unit: Unit file vncserver-x11-serviced.service does not exist.
Failed to start vncserver-x11-serviced.service: Unit vncserver-x11-serviced.service not found.

Attempting to make a backup of /etc/gdm3/custom.conf...
'/etc/gdm3/custom.conf' -> '/etc/gdm3/custom.conf.bkup.20210825-142209'
total 64K
-rw-r--r--   1 root root 1.5K Feb 25 20:42 greeter.dconf-defaults
-rw-r--r--   1 root root  554 Feb 25 20:42 custom.conf
-rw-r--r--   1 root root  996 Feb 25 20:42 config-error-dialog.sh
-rwxr-xr-x   1 root root 6.4K Feb 25 20:42 Xsession
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 Init
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 PostLogin
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 PostSession
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 PreSession
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 Prime
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 PrimeOff
drwxr-xr-x 140 root root  12K Aug 25 14:21 ..
-rw-r--r--   1 root root  554 Aug 25 14:22 custom.conf.bkup.20210825-142209
drwxr-xr-x   8 root root 4.0K Aug 25 14:22 .

Attempting to modify /etc/gdm3/custom.conf
Un-commenting WaylandEnable=false in file.

RealVNC Server : "realvnc-vnc-server_6.7.2.43081_arm64.deb" has been installed.

The system needs to be rebooted.
Would you like to reboot it now?
Enter 'y' for yes or 'n' for No :
y
Rebooting System...
Connection to 192.168.0.18 closed by remote host.
Connection to 192.168.0.18 closed.
====================================

PARTIAL WORKAROUND (under triage)
1) manually install missing library
$ sudo apt get libraspberrypi0

2) re-run the installation script
$ sudo ./install-real-vnc-server-rpi4-8gb-ubuntu.sh

====================================
No LSB modules are available.
You are about to install RealVNC Server for RaspberryPi4 8gb
realvnc-vnc-server_6.7.2.43081_arm64.deb

Checking to see if this version of Ubuntu for RaspberryPi is supported by script...
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
is supported by this script.
Would you like to continue?
Enter 'y' for yes or 'n' for No :
y

Installing VNC Server : "realvnc-vnc-server_6.7.2.43081_arm64.deb"...
--2021-08-25 15:14:33--  https://archive.raspberrypi.org/debian/pool/main/r/realvnc-vnc/realvnc-vnc-server_6.7.2.43081_arm64.deb
Resolving archive.raspberrypi.org (archive.raspberrypi.org)... 93.93.135.141, 46.235.227.39, 176.126.240.86, ...
Connecting to archive.raspberrypi.org (archive.raspberrypi.org)|93.93.135.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9075008 (8.7M) [application/x-debian-package]
Saving to: ‘realvnc-vnc-server_6.7.2.43081_arm64.deb.1’

realvnc-vnc-server_6.7.2.4308 100%[=================================================>]   8.65M  12.8MB/s    in 0.7s

2021-08-25 15:14:34 (12.8 MB/s) - ‘realvnc-vnc-server_6.7.2.43081_arm64.deb.1’ saved [9075008/9075008]

(Reading database ... 179295 files and directories currently installed.)
Preparing to unpack realvnc-vnc-server_6.7.2.43081_arm64.deb ...
Unpacking realvnc-vnc-server (6.7.2.43081) over (6.7.2.43081) ...
Setting up realvnc-vnc-server (6.7.2.43081) ...
Updating /etc/pam.d/vncserver
Updating /etc/pam.conf... done

NOTICE: common configuration in /etc/pam.d contains the following modules:
   pam_sss.so
The default vncserver PAM configuration only enables pam_unix. See
`man vncinitconfig' for details on any manual configuration required.

Looking for font path... not found.
Installed systemd unit for VNC Server in Service Mode daemon
Start or stop the service with:
  systemctl (start|stop) vncserver-x11-serviced.service
Mark or unmark the service to be started at boot time with:
  systemctl (enable|disable) vncserver-x11-serviced.service

Installed systemd unit for VNC Server in Virtual Mode daemon
Start or stop the service with:
  systemctl (start|stop) vncserver-virtuald.service
Mark or unmark the service to be started at boot time with:
  systemctl (enable|disable) vncserver-virtuald.service

Processing triggers for mailcap (3.68ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for shared-mime-info (2.0-1) ...

Creating symlink for the following files :
attempting to create symlink file "/usr/lib/libvchiq_arm.so.0"...
ln: failed to create symbolic link '/usr/lib/libvchiq_arm.so.0': File exists
attempting to create symlink file "/usr/lib/libbcm_host.so.0"...
ln: failed to create symbolic link '/usr/lib/libbcm_host.so.0': File exists
attempting to create symlink file "/usr/lib/libvcos.so.0"...
ln: failed to create symbolic link '/usr/lib/libvcos.so.0': File exists
attempting to create symlink file "/usr/lib/libmmal.so.0"...
ln: failed to create symbolic link '/usr/lib/libmmal.so.0': File exists
attempting to create symlink file "/usr/lib/libmmal_core.so.0"...
ln: failed to create symbolic link '/usr/lib/libmmal_core.so.0': File exists
attempting to create symlink file "/usr/lib/libmmal_components.so.0"...
ln: failed to create symbolic link '/usr/lib/libmmal_components.so.0': File exists
attempting to create symlink file "/usr/lib/libmmal_util.so.0"...
ln: failed to create symbolic link '/usr/lib/libmmal_util.so.0': File exists
attempting to create symlink file "/usr/lib/libmmal_vc_client.so.0"...
ln: failed to create symbolic link '/usr/lib/libmmal_vc_client.so.0': File exists
attempting to create symlink file "/usr/lib/libvcsm.so.0"...
ln: failed to create symbolic link '/usr/lib/libvcsm.so.0': File exists
attempting to create symlink file "/usr/lib/libcontainers.so.0"...
ln: failed to create symbolic link '/usr/lib/libcontainers.so.0': File exists

Enabling and starting the necessary services...
Enabling and starting the service "vncserver-virtuald.service"...
Created symlink /etc/systemd/system/multi-user.target.wants/vncserver-virtuald.service → /lib/systemd/system/vncserver-virtuald.service.
Enabling and starting the service "vncserver-x11-serviced.service"...
Created symlink /etc/systemd/system/multi-user.target.wants/vncserver-x11-serviced.service → /lib/systemd/system/vncserver-x11-serviced.service.

Attempting to make a backup of /etc/gdm3/custom.conf...
'/etc/gdm3/custom.conf' -> '/etc/gdm3/custom.conf.bkup.20210825-151535'
total 68K
-rw-r--r--   1 root root 1.5K Feb 25 20:42 greeter.dconf-defaults
-rw-r--r--   1 root root  996 Feb 25 20:42 config-error-dialog.sh
-rwxr-xr-x   1 root root 6.4K Feb 25 20:42 Xsession
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 Init
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 PostLogin
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 PostSession
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 PreSession
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 Prime
drwxr-xr-x   2 root root 4.0K Aug 25 11:07 PrimeOff
-rw-r--r--   1 root root  554 Aug 25 14:22 custom.conf.bkup.20210825-142209
-rw-r--r--   1 root root  554 Aug 25 14:22 custom.conf
drwxr-xr-x 141 root root  12K Aug 25 15:15 ..
-rw-r--r--   1 root root  554 Aug 25 15:15 custom.conf.bkup.20210825-151535
drwxr-xr-x   8 root root 4.0K Aug 25 15:15 .

Attempting to modify /etc/gdm3/custom.conf
Un-commenting WaylandEnable=false in file.

RealVNC Server : "realvnc-vnc-server_6.7.2.43081_arm64.deb" has been installed.

The system needs to be rebooted.
Would you like to reboot it now?
Enter 'y' for yes or 'n' for No :
y
Rebooting System...
Connection to 192.168.0.18 closed by remote host.
Connection to 192.168.0.18 closed.
====================================

3) reboot and check for open ports for the VNC server – client should now connect although with a “cannot currently show the desktop” error message (still under triagec, if i find the root cause will update everyone)

$ sudo ss -ltpn
State    Recv-Q   Send-Q     Local Address:Port       Peer Address:Port   Process
LISTEN   0        5                0.0.0.0:5900            0.0.0.0:*       users:(("vncserver-x11-c",pid=1791,fd=12))
LISTEN   0        5                0.0.0.0:5999            0.0.0.0:*       users:(("vncserver-virtu",pid=1777,fd=7))
LISTEN   0        4096       127.0.0.53%lo:53              0.0.0.0:*       users:(("systemd-resolve",pid=1664,fd=13))
LISTEN   0        128              0.0.0.0:22              0.0.0.0:*       users:(("sshd",pid=1877,fd=3))
LISTEN   0        128            127.0.0.1:631             0.0.0.0:*       users:(("cupsd",pid=1772,fd=7))
LISTEN   0        5                   [::]:5900               [::]:*       users:(("vncserver-x11-c",pid=1791,fd=11))
LISTEN   0        5                   [::]:5999               [::]:*       users:(("vncserver-virtu",pid=1777,fd=6))
LISTEN   0        128                 [::]:22                 [::]:*       users:(("sshd",pid=1877,fd=4))
LISTEN   0        128                [::1]:631                [::]:*       users:(("cupsd",pid=1772,fd=6))

**Comment by mtbiker-s** [comment]
@codefun sorry you ran into this, if I add the the missing lib **sudo apt get libraspberrypi0** to the script, will that resolve the issue?

**Comment by b-around** [comment]
Kind of - the screen will be black (so the desktop isn't available) but I at least the vnc server will start. 
Let me see what else may be missing in your script to make it work from a clean sever os and I'll update you.

**Comment by mtbiker-s** [comment]
@codefun sounds good, will put the fix in development branch over the weekend. I appreciate your time.

**Comment by mtbiker-s** [comment]
@codefun I added the logic to add that missing lib
https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc/blob/development/install-real-vnc-server-rpi4-8gb-ubuntu.sh#L106
You can download the script from the [development](https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc/tree/development) branch to test it out if you want. I know it wont resolve the issue of the VNC client showing a black screen but at least one step forward. Let me know if you find the other fix. Once it gets resolved well merge it over to the main branch.

**Comment by b-around** [comment]
ThanksI'll be doing a clean os install over the weekend, will test the new version and let you know how it goes. Out of curiosity,  which ubuntu version have you been using and with which desktop environment?On 27 Aug 2021 19:32, mtbiker-s ***@***.***> wrote:
@codefun I added the logic to add that missing lib
https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc/blob/development/install-real-vnc-server-rpi4-8gb-ubuntu.sh#L106
You can download the script from the development branch to test it out if you want. I know it wont resolve the issue of the VNC client showing a black screen but at least one step forward. Let me know if you find the other fix. Once it gets resolved well merge it over to the main branch.

**Comment by mtbiker-s** [comment]
This is my current dev environment on RPi with Hirsute Hippo
It was take via VNC Client while I remoted to the machine 

![image](https://user-images.githubusercontent.com/3429367/131192896-250455ae-36f7-40bc-8c4c-ca71955abdec.png)

**Comment by b-around** [comment]
Tested the script from the development branch and I would suggest changing the order of the libraries installs (having them before the VNC server install else we still get some errors). With the suggested order change the installation goes ok.

I’ve attached the console outputs with current version and tweaked version plus the updated script (apologies doing it dirty and not branching and creating a pull request)

Regarding the display error, I managed to get VNC showing the screen when adding the hdmi_safe=1 param to the config.txt. The annoying part is that I am limited to 680x480 resolution until if figure out why higher resolutions just don't work.
 
Anyway, from my perspective the dependencies issue is sorted and you could move the tweaks to the main branch.

Thanks for the support


[output-current-version.txt](https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc/files/7071598/output-current-version.txt)

[output-tweaked-version.txt](https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc/files/7071599/output-tweaked-version.txt)

[tweaked-install.txt](https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc/files/7071602/tweaked-install.txt)

**Comment by mtbiker-s** [comment]
@codefun thanks so much for providing the changes. I created a new branch called [codefun](https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc/tree/codefun) with the fix you provided and merged the changes to the [main](https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc/tree/main) branch. I appreciate all the testing you did and providing the solution. Closing out the issue.
