### ISSUE TITLE
Documentation regarding launching post install

### ISSUE THREAD

**Issue by jimmodo** [mtbiker-s/ubuntu20.10-rpi-install-vnc#7]
Hi, i installed this in 21.04 and it seems to have installed correctly, my question is how do you open it to configure settings? I dont see the icon in the menu bar like in raspbian post install and restart.

**Comment by mtbiker-s** [comment]
Hi @jimmodo ,
I think this is the closest you'll get to that configuration

<img width="262" alt="vnc-options" src="https://user-images.githubusercontent.com/3429367/133853188-4cebcc13-5472-4216-ad31-6a37ba3d5199.png">

Right click on VNC icon on your host you are trying to remote too, then select "Options"
It should prompt you for a password.

I hope this helps out.

**Comment by mtbiker-s** [comment]
Closing issue, no feedback from @jimmodo
